#!/usr/bin/env python3
"""Extract the AHETPI hourly-earnings series from the local FRED export.

Reads ``samples/08-fred/AHETPI.xlsx`` (Monthly sheet) and emits
``data/series/hourly-earnings-total-private.toml``.

AHETPI = Average Hourly Earnings of Production and Nonsupervisory Employees,
Total Private (CES0500000008), monthly, seasonally adjusted, dollars/hour.
The export runs 1964-01 through 2026-06. We annualize by taking the arithmetic
mean of the 12 months for each year that has a complete Jan-Dec set, 1964-2024
(the plan's window; 2025/2026 are partial and dropped). Non-monetary-in-cents
(a wage RATE in dollars) -> ``values`` (floats).

Drift note: ``fred-ahetpi`` facts carry ``amount_minor`` (cents) but no
``quantity``, and the drift detector's float branch keys on ``quantity``, so no
drift failure can arise here. We still verify the 2024 average ~= $30.12 by eye.
"""

from __future__ import annotations

import datetime
import sys
from collections import defaultdict
from pathlib import Path

import openpyxl

REPO = Path(__file__).resolve().parent.parent
XLSX = REPO / "samples" / "08-fred" / "AHETPI.xlsx"
OUT = REPO / "data" / "series" / "hourly-earnings-total-private.toml"
START_YEAR, END_YEAR = 1964, 2024


def main() -> int:
    if not XLSX.is_file():
        print(f"ERROR: {XLSX} not found", file=sys.stderr)
        return 1
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb["Monthly"]
    months: dict[int, list[float]] = defaultdict(list)
    for r in range(2, ws.max_row + 1):
        date = ws.cell(row=r, column=1).value
        val = ws.cell(row=r, column=2).value
        if not isinstance(date, datetime.datetime) or not isinstance(val, int | float):
            continue
        months[date.year].append(float(val))

    values: dict[int, float] = {}
    for y in range(START_YEAR, END_YEAR + 1):
        obs = months.get(y, [])
        if len(obs) != 12:
            continue  # incomplete year -> gap (only 2025/2026 are partial here)
        values[y] = round(sum(obs) / 12.0, 4)

    yrs = sorted(values)
    notes = (
        "FRED AHETPI monthly, seasonally adjusted, annualized by averaging "
        "12 months per year. Covers all private-sector production/nonsupervisory "
        "employees (not manufacturing-only)."
    )
    lines = [
        f"# Auto-generated by scripts/ahetpi_extract.py from {XLSX.name}",
        "# AHETPI (CES0500000008), monthly seasonally adjusted, annualized as the",
        f"# mean of 12 months. Coverage: {yrs[0]}-{yrs[-1]} (complete years only).",
        "",
        "[[series]]",
        'id = "hourly-earnings-total-private"',
        'label = "Average hourly earnings, total private production/nonsupervisory"',
        'source = "fred-ahetpi"',
        'tier = "A"',
        'unit = "USD per hour, nominal (annual mean of 12 monthly values)"',
        'population = "Production and nonsupervisory employees, total private sector"',
        f'notes = "{notes}"',
        "",
        "[series.values]",
    ]
    for y in yrs:
        lines.append(f"{y} = {values[y]:.4f}")
    lines.append("")
    OUT.write_text("\n".join(lines))
    # Report a few spot-check anchors.
    for y in (1964, 1980, 1990, 2000, 2010, 2024):
        print(f"  {y}: ${values[y]:.4f}/hr  (n={len(months[y])} months)")
    print(f"hourly-earnings-total-private: {len(values)} years "
          f"({yrs[0]}-{yrs[-1]}) -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
