#!/usr/bin/env python3
"""Extract CPI-U *component* annual-average series from the BLS Public Data API.

Emits ``data/series/cpi-food.toml``, ``cpi-rent.toml`` and ``cpi-apparel.toml``
(1913-2024). The all-items counterpart lives in ``bls_cpi_extract.py``; this
script is its component sibling and shares its conventions — period ``M13``
official annual averages only, 10-year chunking, non-zero exit when the API is
unreachable so a gap is surfaced rather than silently filled.

Why these three. The 1910s, 1920s and 1930s rooms carry declared gaps for
income, the food basket and housing, because no national family-income or
consumer-expenditure survey exists before the 1940s. The *price* record for
those decades is nevertheless excellent: BLS has published food, rent and
apparel indexes continuously since 1913. Component indexes cannot reconstruct a
household budget and do not close those gaps — but they do let the early rooms
show, from a Tier A source, how the price of eating and the price of shelter
actually moved, which those rooms currently cannot show at all.

Transcription note. These values were taken from the API rather than from the
scanned Historical Statistics table (series L 40-47) that carries the same data.
That volume's PDF text layer is OCR'd badly enough to be unusable for
curation — it renders zeros as ".0", so 100.0 reads as "1.0.0 . .0" and 106.3
as "1.06.3", and two independent extractors reproduce the same corruption. A
machine-readable source with no transcription step is strictly safer than a
careful reading of a bad scan.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

import requests

REPO = Path(__file__).resolve().parent.parent
START_YEAR, END_YEAR = 1913, 2024
CHUNK = 10
API_URL = "https://api.bls.gov/publicAPI/v2/timeseries/data/"

# series id -> (output stem, series id in vitrine, label, unit tail, population)
COMPONENTS: dict[str, tuple[str, str, str, str]] = {
    "CUUR0000SAF1": (
        "cpi-food",
        "CPI-U: food, U.S. city average, annual average",
        "All Urban Consumers (CPI-U), U.S. city average, food",
        "food",
    ),
    "CUUR0000SEHA": (
        "cpi-rent",
        "CPI-U: rent of primary residence, U.S. city average, annual average",
        "All Urban Consumers (CPI-U), U.S. city average, rent of primary residence",
        "rent of primary residence",
    ),
    "CUUR0000SAA": (
        "cpi-apparel",
        "CPI-U: apparel, U.S. city average, annual average",
        "All Urban Consumers (CPI-U), U.S. city average, apparel",
        "apparel",
    ),
}


def _pull_chunk(
    series_ids: list[str], start: int, end: int, key: str | None
) -> dict[str, dict[int, float]]:
    body: dict[str, object] = {
        "seriesid": series_ids,
        "startyear": str(start),
        "endyear": str(end),
        "calculations": False,
        "annualaverage": True,
    }
    # The registration key must travel in the JSON body; in a header it is
    # silently ignored and the unregistered 25/day cap applies.
    if key:
        body["registrationkey"] = key
    last_err = ""
    for _attempt in range(3):
        try:
            response = requests.post(
                API_URL, json=body, headers={"Content-Type": "application/json"}, timeout=60
            )
            if response.status_code == 429:
                time.sleep(15)
                continue
            data = response.json()
            if data.get("status") != "REQUEST_SUCCEEDED":
                last_err = json.dumps(data.get("message", data))
                time.sleep(3)
                continue
            out: dict[str, dict[int, float]] = {sid: {} for sid in series_ids}
            for series in data["Results"]["series"]:
                for obs in series["data"]:
                    if obs.get("period") == "M13":
                        out[series["seriesID"]][int(obs["year"])] = float(obs["value"])
            return out
        except (requests.RequestException, ValueError, KeyError) as exc:
            last_err = repr(exc)
            time.sleep(3)
    raise RuntimeError(f"BLS API chunk {start}-{end} failed: {last_err}")


def _render(
    series_id: str, stem: str, label: str, population: str, values: dict[int, float]
) -> str:
    years = sorted(values)
    notes = (
        f"BLS series {series_id}, official annual averages (period M13) via the "
        f"BLS Public Data API."
    )
    lines = [
        "# Auto-generated by scripts/bls_cpi_components_extract.py from the BLS Public Data API",
        f"# Series {series_id}, annual averages.",
        f"# Coverage: {years[0]}-{years[-1]} (period M13 official annual averages).",
        "",
        "[[series]]",
        f'id = "{stem}"',
        f'label = "{label}"',
        'source = "bls-api"',
        'tier = "A"',
        'unit = "CPI-U index (1982-84=100), annual average"',
        f'population = "{population}"',
        f'notes = "{notes}"',
        "",
        "[series.values]",
    ]
    lines.extend(f"{year} = {values[year]}" for year in years)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    key = os.environ.get("BLS_API_KEY")
    series_ids = list(COMPONENTS)
    collected: dict[str, dict[int, float]] = {sid: {} for sid in series_ids}

    for start in range(START_YEAR, END_YEAR + 1, CHUNK):
        end = min(start + CHUNK - 1, END_YEAR)
        chunk = _pull_chunk(series_ids, start, end, key)
        for sid, values in chunk.items():
            collected[sid].update(values)
        print(
            f"  chunk {start}-{end}: "
            + ", ".join(f"{sid}={len(v)}" for sid, v in chunk.items()),
            file=sys.stderr,
        )
        time.sleep(1)  # be a good citizen

    exit_code = 0
    for sid, (stem, label, population, _short) in COMPONENTS.items():
        values = collected[sid]
        if not values:
            print(f"ERROR: no data retrieved for {sid}", file=sys.stderr)
            exit_code = 1
            continue
        out_path = REPO / "data" / "series" / f"{stem}.toml"
        out_path.write_text(_render(sid, stem, label, population, values))
        years = sorted(values)
        print(
            f"{stem}: {len(values)} years ({years[0]}-{years[-1]}) -> "
            f"{out_path.relative_to(REPO)}"
        )
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
