#!/usr/bin/env python3
"""Extract the CPI-U annual-average series from the BLS Public Data API.

Emits ``data/series/cpi-u.toml`` (source ``fred-cpiaucns``), 1913-2024, using
BLS series CUUR0000SA0 annual averages (period M13). Non-monetary index ->
``values`` (floats).

The BLS API caps a single request at 20 years, so the window is chunked. A
registered key (``BLS_API_KEY`` from samples/api.env) is used when present.
Only period ``M13`` (Annual) rows are taken; the official annual average beats
re-averaging 12 monthly values. If the API is unreachable the script exits
non-zero so the gap is surfaced, not silently filled.

Drift note: the ``fred-cpiaucns`` facts carry ``quantity`` but no ``price_year``
(``py=None``), so the drift detector skips them. We still eyeball CPI[1950] and
CPI[2024] against the corpus's stated values.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

import requests

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "series" / "cpi-u.toml"
SERIES_ID = "CUUR0000SA0"
START_YEAR, END_YEAR = 1913, 2024
# BLS API allows up to 20 years/request with a valid key, 10 without. We use a
# 10-year chunk so extraction is complete regardless of whether the registered
# key is honored (12 requests stays well under the daily cap).
CHUNK = 10
API_URL = "https://api.bls.gov/publicAPI/v2/timeseries/data/"


def _pull_chunk(start: int, end: int, key: str | None) -> dict[int, float]:
    body = {
        "seriesid": [SERIES_ID],
        "startyear": str(start),
        "endyear": str(end),
        "calculations": False,
        "annualaverage": True,
    }
    # BLS API v2 requires the registration key in the JSON BODY (not a header);
    # in a header it is silently ignored and the unregistered 25/day cap applies.
    if key:
        body["registrationkey"] = key
    headers = {"Content-Type": "application/json"}
    last_err = ""
    for _attempt in range(3):
        try:
            r = requests.post(API_URL, json=body, headers=headers, timeout=60)
            if r.status_code == 429:
                time.sleep(15)
                continue
            data = r.json()
            if data.get("status") != "REQUEST_SUCCEEDED":
                last_err = json.dumps(data.get("message", data))
                time.sleep(3)
                continue
            out: dict[int, float] = {}
            for s in data["Results"]["series"]:
                for obs in s["data"]:
                    if obs.get("period") == "M13":
                        out[int(obs["year"])] = float(obs["value"])
            return out
        except (requests.RequestException, ValueError, KeyError) as exc:
            last_err = repr(exc)
            time.sleep(3)
    raise RuntimeError(f"BLS API chunk {start}-{end} failed: {last_err}")


def main() -> int:
    key = os.environ.get("BLS_API_KEY")
    values: dict[int, float] = {}
    for start in range(START_YEAR, END_YEAR + 1, CHUNK):
        end = min(start + CHUNK - 1, END_YEAR)
        chunk = _pull_chunk(start, end, key)
        print(f"  chunk {start}-{end}: {len(chunk)} annual averages", file=sys.stderr)
        values.update(chunk)
        time.sleep(1)  # be a good citizen

    yrs = sorted(values)
    if not yrs:
        print("ERROR: no CPI data retrieved", file=sys.stderr)
        return 1
    missing = sorted(set(range(START_YEAR, END_YEAR + 1)) - set(yrs))
    notes = (
        "BLS series CUUR0000SA0, official annual averages (period M13) via the "
        "BLS Public Data API."
    )
    lines = [
        "# Auto-generated by scripts/bls_cpi_extract.py from the BLS Public Data API",
        "# Series CUUR0000SA0 (CPI-U, all items, U.S. city average), annual averages.",
        f"# Coverage: {yrs[0]}-{yrs[-1]} (period M13 official annual averages).",
        "",
        "[[series]]",
        'id = "cpi-u"',
        'label = "CPI-U: all items, U.S. city average, annual average"',
        'source = "fred-cpiaucns"',
        'tier = "A"',
        'unit = "CPI-U index (1982-84=100), annual average"',
        'population = "All Urban Consumers (CPI-U), U.S. city average, all items"',
        f'notes = "{notes}"',
        "",
        "[series.values]",
    ]
    for y in yrs:
        lines.append(f"{y} = {values[y]}")
    lines.append("")
    OUT.write_text("\n".join(lines))
    for y in (1913, 1950, 1980, 2010, 2024):
        if y in values:
            print(f"  CPI[{y}] = {values[y]}")
    print(f"cpi-u: {len(values)} years ({yrs[0]}-{yrs[-1]})"
          + (f", missing: {missing}" if missing else "")
          + f" -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
