#!/usr/bin/env python3
"""Extract the Plan 027 WI-4b workplace-death series from BLS CFOI.

Emits ``data/series/us-workplace-death-rate.toml`` from the nineteen per-year
BLS "hours-based rates" workbooks archived in
``samples/44-road-workplace-deaths/hb-YYYY.xlsx`` (2006-2024).

**The series is short, and that is the exhibit.** The Census of Fatal
Occupational Injuries has only been "active in all 50 States and the District
of Columbia since 1992" (BLS's own survey definition, archived beside the
workbooks); before that there was no federal census of people killed at work
at all. BLS then changed how the rate is computed: from 2006 it is hours-based
(fatalities per 100,000 full-time-equivalent workers, from CPS hours), where
before it was employment-based. BLS states the change explicitly, so the two
are different measures and are not chained here. What this file carries is the
one continuous, single-measure stretch the record actually supports.

**Columns are located by header text, not position.** The workbooks' layout
changes three times across the nineteen years -- 2006-2016 have no
"Characteristic code" column, 2017-2018 add one *and* a fatality-count column,
2019+ drop the count again -- so a fixed column index silently reads hours as
a rate for two of the years. That is not hypothetical: it happened, and was
caught by the cross-check below.

**Cross-check.** The 2006-2017 values are checked against a second,
independently-published BLS document: the data labels on the "Rate of fatal
work injuries per 100,000 full-time equivalent workers" chart in
``cfoi-charts-1992-2017.pdf``.

Spot-verification: see docs/verification-log.md, Plan 027 WI-4b.
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ARCHIVE = REPO / "samples" / "44-road-workplace-deaths"
OUT = REPO / "data" / "series" / "us-workplace-death-rate.toml"

FIRST_YEAR, LAST_YEAR = 2006, 2024
CFOI_BEGINS = 1992          # BLS: CFOI active in all 50 states since 1992
HOURS_BASIS_BEGINS = 2006   # BLS: hours-based rates replace employment-based

RATE_HEADER = "fatal injury rate"
TOTAL_ROW = "Total"

# the chart data labels from cfoi-charts-1992-2017.pdf, page 2 ("Rate of fatal
# work injuries per 100,000 full-time equivalent workers by employee status,
# 2006-17"), All Workers series -- an independent BLS witness
CHART_LABELS: dict[int, float] = {
    2006: 4.2, 2007: 4.0, 2008: 3.7, 2009: 3.5, 2010: 3.6, 2011: 3.5,
    2012: 3.4, 2013: 3.3, 2014: 3.4, 2015: 3.4, 2016: 3.6, 2017: 3.5,
}


def _rate_for(year: int) -> float:
    import openpyxl

    wb = openpyxl.load_workbook(ARCHIVE / f"hb-{year}.xlsx", data_only=True)
    ws = wb[wb.sheetnames[0]]
    rows = list(ws.iter_rows(min_row=1, max_row=12, values_only=True))

    header_idx = rate_col = None
    for i, row in enumerate(rows):
        cells = [("" if v is None else str(v)).strip() for v in row]
        if cells and cells[0] == "Characteristic":
            header_idx = i
            for j, cell in enumerate(cells):
                if cell.lower().startswith(RATE_HEADER):
                    rate_col = j
            break
    if header_idx is None or rate_col is None:
        raise SystemExit(f"{year}: no 'Characteristic' header row with a rate column")

    for row in rows[header_idx + 1 :]:
        cells = [("" if v is None else str(v)).strip() for v in row]
        if cells and cells[0] == TOTAL_ROW:
            raw = row[rate_col]
            if raw is None or str(raw).strip() == "":
                raise SystemExit(f"{year}: the Total row has no rate")
            return float(raw)
    raise SystemExit(f"{year}: no '{TOTAL_ROW}' row found")


def parse_all() -> dict[int, float]:
    """Published rates, rounded to the one decimal place BLS publishes.

    2018's workbook carries the unrounded figure (3.4806…) where every other
    year carries one decimal place. Rounding it matches BLS's own published
    value; the assertion below proves rounding is a no-op everywhere else, so
    it cannot quietly change a year that was already published rounded.
    """
    raw = {y: _rate_for(y) for y in range(FIRST_YEAR, LAST_YEAR + 1)}
    rounded = {y: round(v, 1) for y, v in raw.items()}
    changed = {y for y in raw if abs(raw[y] - rounded[y]) > 1e-9}
    if changed - {2018}:
        raise SystemExit(
            f"rounding changed years other than 2018: {sorted(changed - {2018})}"
        )
    return rounded


def cross_check(rates: dict[int, float]) -> list[tuple[int, float, float]]:
    return [
        (y, rates[y], CHART_LABELS[y])
        for y in CHART_LABELS
        if abs(rates[y] - CHART_LABELS[y]) > 1e-9
    ]


def render_toml(rates: dict[int, float]) -> str:
    lines = [
        "# Auto-generated by scripts/bls_cfoi_rates_extract.py from the BLS CFOI",
        "# hours-based rate workbooks (samples/44-road-workplace-deaths/ — see the",
        "# source registry entry and the verification log, Plan 027 WI-4b, before",
        "# editing by hand).",
        "",
        "[[series]]",
        'id = "us-workplace-death-rate"',
        'label = "Fatal work injuries per 100,000 full-time-equivalent workers, 2006-2024"',
        'source = "bls-cfoi-hours-based-rates"',
        'tier = "A"',
        'unit = "fatal work injuries per 100,000 full-time-equivalent workers"',
        'population = "All US workers, employed and self-employed, measured against total '
        'hours worked from the Current Population Survey"',
        'notes = "The whole series, because the whole series is this short. The Census of '
        "Fatal Occupational Injuries has covered all 50 states and DC only since 1992 — "
        "before that the United States kept no federal census of people killed at work — and "
        "BLS changed the rate's basis in 2006 from employment to hours worked, so figures "
        "before 2006 measure something else and are not chained on. Rate = (fatal work "
        "injuries / total hours worked) x 200,000,000, the base for 100,000 full-time "
        'equivalents at 40 hours a week for 50 weeks."',
        "",
        "[series.values]",
    ]
    for year in sorted(rates):
        lines.append(f"{year} = {rates[year]:.1f}")
    return "\n".join(lines) + "\n"


def main() -> None:
    rates = parse_all()
    years = sorted(rates)
    if years != list(range(FIRST_YEAR, LAST_YEAR + 1)):
        raise SystemExit(f"expected {FIRST_YEAR}-{LAST_YEAR}, got {years[0]}-{years[-1]}")

    differences = cross_check(rates)
    if differences:
        raise SystemExit(
            "workbook rates disagree with the BLS chart's own data labels: "
            f"{differences}"
        )

    OUT.write_text(render_toml(rates))
    print(f"wrote {OUT.relative_to(REPO)}: {len(rates)} values {years[0]}-{years[-1]}")
    print(f"cross-check vs cfoi-charts-1992-2017.pdf: {len(CHART_LABELS)} years compared, "
          f"0 differing")
    print()
    print("== the whole series ==")
    for year in years:
        print(f"  {year}  {rates[year]:.1f}")
    print()
    print("== what is absent, and why ==")
    print(f"  before {CFOI_BEGINS}: no federal census of workplace fatalities existed")
    print(f"  {CFOI_BEGINS}-{HOURS_BASIS_BEGINS - 1}: rates published on an employment "
          f"basis — a different measure, not chained")


if __name__ == "__main__":
    main()
