#!/usr/bin/env python3
"""Extract the median-home-value series (split into two series, two sources).

Emits two series under ``data/series/``:

* ``median-home-value-decennial`` — source ``census-homeownership-historical``,
  decennial census median values 1940-2000. Read from
  ``samples/05-census-housing/values-unadj.txt`` (the U.S. row).
* ``median-home-value-acs`` — source ``census-acs-homevalue``, ACS 1-year
  Table B25077 median values. Read from every ``ACSDT1Y*.B25077-*.csv`` in
  ``samples/06-acs-csv/``.

Both are monetary -> ``values_minor`` (integer cents). Only the years whose CSV
is present locally are emitted for the ACS series; missing years render as gaps.

Drift: ``median-home-value-acs`` is the unique series for its source, so the
2010 value MUST equal the curated fact ``us-2010s-median-home-value``
(amount_minor 17990000). The decennial series is the unique series for
``census-homeownership-historical``, so each decennial value must equal the
matching ``us-<decade>s-median-home-value`` fact. Both are verified by eye.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "data" / "series"
DECENNIAL_TXT = REPO / "samples" / "05-census-housing" / "values-unadj.txt"
ACS_DIR = REPO / "samples" / "06-acs-csv"


def _emit(sid: str, label: str, source: str, population: str, notes: str,
          values_minor: dict[int, int]) -> Path:
    values_minor = dict(sorted(values_minor.items()))
    yrs = sorted(values_minor)
    lines = [
        "# Auto-generated by scripts/home_value_extract.py",
        f"# Coverage: {yrs[0]}-{yrs[-1]} ({len(yrs)} values). Values are integer cents.",
        "",
        "[[series]]",
        f'id = "{sid}"',
        f'label = "{label}"',
        f'source = "{source}"',
        'tier = "A"',
        'unit = "USD, nominal (median value of owner-occupied housing)"',
        f'population = "{population}"',
        f'notes = "{notes}"',
        "",
        "[series.values_minor]",
    ]
    for y in yrs:
        lines.append(f"{y} = {values_minor[y]}")
    lines.append("")
    out = OUT_DIR / f"{sid}.toml"
    out.write_text("\n".join(lines))
    return out


def extract_decennial() -> dict[int, int]:
    """Parse values-unadj.txt: header years + the 'United States' dollar row."""
    text = DECENNIAL_TXT.read_text()
    years: list[int] = []
    us_values: list[int] = []
    for line in text.splitlines():
        toks = line.split()
        if not toks:
            continue
        # Header row: tokens are all 4-digit years.
        if len(years) == 0 and all(re.fullmatch(r"\d{4}", t) for t in toks):
            years = [int(t) for t in toks]
            continue
        # United States row: first token 'United' 'States', then $ amounts.
        if toks[0] == "United" and "States" in toks:
            money = [t for t in toks if t.startswith("$")]
            us_values = [int(t.replace("$", "").replace(",", "")) for t in money]
    if len(years) != len(us_values) or not years:
        raise RuntimeError(
            f"could not parse decennial home values: years={years} values={us_values}"
        )
    return {y: v * 100 for y, v in zip(years, us_values, strict=True)}


def extract_acs() -> dict[int, int]:
    """Parse each ACSDT1Y*.B25077-*.csv: year from filename, estimate from row."""
    out: dict[int, int] = {}
    for path in sorted(ACS_DIR.glob("ACSDT1Y*.B25077-*.csv")):
        m = re.search(r"ACSDT1Y(\d{4})\.B25077", path.name)
        if not m:
            continue
        year = int(m.group(1))
        with path.open(newline="") as fh:
            reader = csv.reader(fh)
            header = next(reader)
            est_col = None
            for i, h in enumerate(header):
                if "United States" in h and "Estimate" in h:
                    est_col = i
                    break
            if est_col is None:
                raise RuntimeError(f"no US Estimate column in {path.name}")
            for row in reader:
                if row and "median value" in row[0].lower():
                    val = row[est_col].replace(",", "").strip()
                    out[year] = int(val) * 100  # dollars -> cents
                    break
    return out


def main() -> int:
    dec = extract_decennial()
    path = _emit(
        "median-home-value-decennial",
        "Median value of owner-occupied homes (decennial census)",
        "census-homeownership-historical",
        "All U.S. owner-occupied housing units (decennial census, median value)",
        "Decennial census median home values from the Census Historical Housing "
        "Tables (values-unadj.txt, U.S. row). Self-reported owner values; "
        "decennial only before ACS began in 2005.",
        dec,
    )
    for y in sorted(dec):
        print(f"  decennial[{y}] = {dec[y]}")

    acs = extract_acs()
    path2 = _emit(
        "median-home-value-acs",
        "Median value of owner-occupied homes (ACS B25077)",
        "census-acs-homevalue",
        "Owner-occupied housing units (ACS 1-year estimates, Table B25077)",
        "ACS Table B25077 median value of owner-occupied housing units, 1-year "
        "estimates. Only years with a local CSV are present; missing years are gaps.",
        acs,
    )
    for y in sorted(acs):
        print(f"  acs[{y}] = {acs[y]}")
    print(f"median-home-value-decennial: {len(dec)} years -> {path.relative_to(REPO)}")
    print(f"median-home-value-acs: {len(acs)} years -> {path2.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
