#!/usr/bin/env python3
"""Extract the new-car-price series from the curated decade facts.

Emits ``data/series/new-car-price.toml`` (source ``bea-new-car-price``),
the BEA average transaction price per new car (ORNL TEDB Table 11.13).

Why sparse
----------
The full annual series (1970-2020, ~51 values) lives in ORNL Transportation
Energy Data Book Edition 40, Table 11.13, which is NOT present as a local file
under samples/ and is not served by FRED or the BLS API. Rather than invent the
intermediate years, this script projects the already-curated, gate-verified
decade facts (``us-1970s-car-price`` ... ``us-2020s-car-price``) into series
form. Each of those facts transcribes TEDB Table 11.13 with a ``price_year`` and
``amount_minor`` (cents). Re-publishing those same values deterministically
introduces no new number and guarantees series/fact agreement by construction.

Coverage is therefore the six decade-point years (1970, 1980, 1990, 2000, 2010,
2020). The 45 intervening years are GAPS rendered as such. Annual values require
the TEDB table file; fetching it is tracked separately.

Monetary -> ``values_minor`` (integer cents). This is the unique series for its
source, so every value MUST equal its matching ``us-*-car-price`` fact
(drift detector, invariant 9).
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
US_DIR = REPO / "data" / "us"
OUT = REPO / "data" / "series" / "new-car-price.toml"
SOURCE_ID = "bea-new-car-price"


def main() -> int:
    values_minor: dict[int, int] = {}
    for path in sorted(US_DIR.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        for fact in data.get("fact", []):
            if fact.get("source") != SOURCE_ID:
                continue
            py = fact.get("price_year")
            am = fact.get("amount_minor")
            if py is None or am is None:
                print(f"WARNING: {fact.get('id')} (source {SOURCE_ID}) lacks "
                      f"price_year/amount_minor — skipped", file=sys.stderr)
                continue
            if py in values_minor and values_minor[py] != am:
                print(f"WARNING: {fact.get('id')} redefines {py} "
                      f"({values_minor[py]} -> {am})", file=sys.stderr)
            values_minor[py] = am

    if not values_minor:
        print(f"ERROR: no facts with source {SOURCE_ID} found", file=sys.stderr)
        return 1

    yrs = sorted(values_minor)
    missing = sorted(set(range(yrs[0], yrs[-1] + 1)) - set(yrs))
    note = (
        "BEA average transaction price per new car (ORNL TEDB Table 11.13, "
        "Edition 40). Sparse: only decade-point years are transcribed from the "
        "curated decade facts; the 45 intervening years are gaps pending the "
        "TEDB annual table file. Domestic + import passenger cars, excluding "
        "pickups, vans, and SUVs."
    )
    lines = [
        "# Auto-generated by scripts/new_car_price_extract.py from curated decade facts",
        f"# (us-*-car-price, source {SOURCE_ID}). Projects TEDB Table 11.13 decade points.",
        f"# Coverage: {yrs[0]}-{yrs[-1]} ({len(yrs)} decade points; intervening years are gaps).",
        "",
        "[[series]]",
        'id = "new-car-price"',
        'label = "Average transaction price per new car (domestic + import)"',
        f'source = "{SOURCE_ID}"',
        'tier = "A"',
        'unit = "USD, nominal (average transaction price)"',
        'population = "All new passenger cars sold in the U.S. (domestic + import), '
        'excluding pickups, vans, and SUVs"',
        f'notes = "{note}"',
        "",
        "[series.values_minor]",
    ]
    for y in yrs:
        lines.append(f"{y} = {values_minor[y]}")
    lines.append("")
    OUT.write_text("\n".join(lines))
    for y in yrs:
        print(f"  car-price[{y}] = {values_minor[y]}")
    print(f"new-car-price: {len(yrs)} decade points ({yrs[0]}-{yrs[-1]}), "
          f"{len(missing)} intervening years are gaps -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
